Repository elvinmatheus/mandacaru.dev-ibiapaba-cdd, pull requests merged in 2023-11, with the labels that each got.

#8 Adicionar EDA do DataSet de Financeiro
  .github/workflows/lint-and-format.yaml
  .gitignore
  Makefile
  config/main.yaml
  data/raw/data.csv
  docs/.gitKeep
  notebooks/1.0-scr-analise-exploratoria.ipynb
  notebooks/Untitled.ipynb
  poetry.lock
  pyproject.toml
  src/__init__.py
  src/config.py
  src/data_loader.py
  src/logger.py
  tests/.gitKeep
Labels: enhancement, DS, Alta

#9 docs: adicionar luan e amarildo no readme
  README.md
Labels: documentation, Baixa

#16 6 tratamento de dados tokenização remoção de stops words e stemming dataset financial sentiment analysis
  config/main.yaml
  data/interim/data.csv
  data/processed/data.csv
  notebooks/1.0-scr-pre-procesamento.ipynb
  notebooks/2.0-lapl-tratamento-dados.ipynb
  notebooks/3.0-emss+cegu-pre-procesamento.ipynb
Labels: Alta
